name: Run Tests

on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - defect/*

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test_playlistory_db
          POSTGRES_PASSWORD: adminadmin
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: run tests
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_TEST_REFRESH_TOKEN: ${{ secrets.SPOTIFY_TEST_REFRESH_TOKEN }}
        run: |
          yarn install
          yarn test
        working-directory: ./api
  docker:
    needs: run-tests
    runs-on: ubuntu-latest
    if: |
      contains('
        refs/heads/master
        refs/heads/develop
      ', github.ref)
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: build
        run: docker-compose build
      - name: push to branch tag
        run: |
          branchName=${GITHUB_REF#refs/heads/}
          docker tag ryanpage/playlistory-api:latest ryanpage/playlistory-api:$branchName-${{ github.run_number }}
          docker tag ryanpage/playlistory-web:latest ryanpage/playlistory-web:$branchName-${{ github.run_number }}
          docker push ryanpage/playlistory-api:$branchName-${{ github.run_number }}
          docker push ryanpage/playlistory-web:$branchName-${{ github.run_number }}
      - name: push to latest
        run: docker-compose push
      